// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVMnyC50Xp24rEcKJ6aZyjgCNEbQ_PdLU',
    appId: '1:946609120688:web:2560b7c84fe9b56ad56275',
    messagingSenderId: '946609120688',
    projectId: 'mini-social-app-2025',
    authDomain: 'mini-social-app-2025.firebaseapp.com',
    storageBucket: 'mini-social-app-2025.firebasestorage.app',
    measurementId: 'G-418694N6DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT5I8w_WpIb88Earb2UJL0fl2pOoz63QE',
    appId: '1:946609120688:android:f0caaf058fd26254d56275',
    messagingSenderId: '946609120688',
    projectId: 'mini-social-app-2025',
    storageBucket: 'mini-social-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlgDoa9gvkUCe44Xg_ywa6YqRmG0tAnsw',
    appId: '1:946609120688:ios:0c5ae4b750746d05d56275',
    messagingSenderId: '946609120688',
    projectId: 'mini-social-app-2025',
    storageBucket: 'mini-social-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlgDoa9gvkUCe44Xg_ywa6YqRmG0tAnsw',
    appId: '1:946609120688:ios:0c5ae4b750746d05d56275',
    messagingSenderId: '946609120688',
    projectId: 'mini-social-app-2025',
    storageBucket: 'mini-social-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.miniSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVMnyC50Xp24rEcKJ6aZyjgCNEbQ_PdLU',
    appId: '1:946609120688:web:95193e917dda088fd56275',
    messagingSenderId: '946609120688',
    projectId: 'mini-social-app-2025',
    authDomain: 'mini-social-app-2025.firebaseapp.com',
    storageBucket: 'mini-social-app-2025.firebasestorage.app',
    measurementId: 'G-R3Z39BE3JQ',
  );
}
